### PR TITLE
fix: Resolve loop device unexpected behaviour

### LINKED ISSUE #674: Encryption flag silently does nothing on loop files
When requesting a loop backed disk with `--encrypt` no encryption occurs and no error or warning is emitted. 

Loop files are intended for development, and not working with FDE is intentional, however the experience of requesting an encrypted loop file, and the result being that you get an unencrypted device is unexpected. The user may expect that FDE is available on the loop file. 

If the `--encrypt` flag is passed to `disk add`, an error should occur.

### PR DESCRIPTION
**Pull request by johnramsden**
# Description

Fixes #674

Loop devices can exhibit unexpected behavior where they are passed encrypt/wal/db flags but it does nothing. FDE/WAL/DB is intended for production usage, so we do not support it on loop devices, but the user experience should be better in case they are trying to test encryption on loop devices and wondering why it's not working.

Fix silent failures when adding loop-backed OSDs:
  - Error on --encrypt with loop devices instead of silently ignoring it
  - Fix missing encryptDevice error handling (err was not assigned)
  - Apply validateAddOSDArgs to single-disk bulk path which previously skipped validation
  - Consolidate loop device detection into isLoopDevice helper
  - Pass WAL/DB through to add disk so we can validate and not ignore WAL/DB
  - Amend old docs

## Type of change

Delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- Clean code (code refactor, test updates; does not introduce functional changes)

## How has this been tested?

* Unit tests adjusted to test WAL/DB/encrypt

Manual test commands:

    sudo microceph cluster bootstrap

    # Should error: encryption on loop device
    sudo microceph disk add loop,4G,3 --encrypt

Validation Error found
Error: encryption is not supported on loop devices

    # Should error: loop device with WAL
    sudo microceph disk add loop,4G,3 --wal-device /dev/sdx

Validation Error found
Error: WAL/DB is not supported on loop devices

    # Should error: loop device with DB
    sudo microceph disk add loop,4G,3 --db-device /dev/sdx

Validation Error found
Error: WAL/DB is not supported on loop devices

    # Should succeed: loop device without encrypt/WAL/DB
    sudo microceph disk add loop,1G,3

```
+-----------+---------+
|   PATH    | STATUS  |
+-----------+---------+
| loop,1G,3 | Success |
+-----------+---------+
```

## Contributor checklist

Please check that you have:

- [x] self-reviewed the code in this PR
- [x] added code comments, particularly in less straightforward areas
- [x] checked and added or updated relevant documentation
- [x] checked and added or updated relevant release notes
- [x] added tests to verify effectiveness of this change

### CODE REVIEW

**Review by sabaini — COMMENTED** [review]
Thanks @johnramsden lgtm! Need to get CI green then it's gtg

File: microceph/ceph/osd.go [hunk 1]
```diff
@@ -191,7 +191,7 @@ func (m *OSDManager) setupEncryptedOSD(devicePath string, osdDataPath string, os
 	}
 
 	// Encrypt the device
-	encryptDevice(devicePath, key)
+	err = encryptDevice(devicePath, key)
```
Comment (UtkarshBhatthere) [inline microceph/ceph/osd.go:194]: nice catch

File: microceph/ceph/osd.go [hunk 2]
```diff
@@ -739,9 +744,20 @@ func (m *OSDManager) addOSD(ctx context.Context, data types.DiskParameter, wal *
...
+}
+
 func (m *OSDManager) validateAddOSDArgs(data types.DiskParameter, wal *types.DiskParameter, db *types.DiskParameter) error {
-	if data.LoopSize != 0 && (wal != nil || db != nil) {
-		return fmt.Errorf("loopback and WAL/DB are mutually exclusive")
+	if isLoopDevice(data) {
+		if wal != nil || db != nil {
+			return fmt.Errorf("loopback and WAL/DB are mutually exclusive")
+		}
+		if data.Encrypt {
```
Comment (UtkarshBhatthere) [inline microceph/ceph/osd.go:758]: is this a limitation that we are imposing ? Because this will make it harder for us to test encryption with loop devices (most of our CI)

**Review by UtkarshBhatthere — COMMENTED** [review]
lgtm, left some comments/ questions

File: microceph/ceph/osd.go (hunk 2 above)
Comment (johnramsden) [reply microceph/ceph/osd.go:758]: It says in the [documentation](https://canonical-microceph.readthedocs-hosted.com/stable/reference/commands/disk/): 

> WAL and DB devices can only be used with data devices that reside on a block device, not with loop files. Loop files do not support encryption.

Additionally, I believe the CI [uses](https://github.com/canonical/microceph/blob/afb6a3a0cb2a28edc1c5d10ef0a16b77ccd56dd7/.github/workflows/tests.yml#L125) manually created loop devices, not microceph managed "loop files" - these will not be identified as different from a block device, and do support encryption.

**Comment by UtkarshBhatthere** [comment]
@johnramsden have triggered the tests.

File: microceph/ceph/osd.go (hunk 2 above)
Comment (UtkarshBhatthere) [reply microceph/ceph/osd.go:758]: ack, that sounds good to me.
